
insert into Cidade (nome, ativo, dataCadastro) values ('Afonso Cláudio', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Água Doce do Norte', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Águia Branca', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Alegre', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Alfredo Chaves', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Alto Rio Novo', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Anchieta', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Apiacá', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Aracruz', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Atilio Vivacqua', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Baixo Guandu', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Barra de São Francisco', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Boa Esperança', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Bom Jesus do Norte', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Brejetuba', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Cachoeiro de Itapemirim', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Cariacica', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Castelo', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Colatina', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Conceição da Barra', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Conceição do Castelo', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Divino de São Lourenço', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Domingos Martins', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Dores do Rio Preto', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Ecoporanga', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Fundão', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Governador Lindenberg', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Guaçuí', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Guarapari', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Ibatiba', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Ibiraçu', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Ibitirama', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Iconha', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Irupi', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Itaguaçu', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Itapemirim', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Itarana', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Iúna', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Jaguaré', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Jerônimo Monteiro', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('João Neiva', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Laranja da Terra', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Linhares', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Mantenópolis', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Marataízes', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Marechal Floriano', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Marilândia', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Mimoso do Sul', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Montanha', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Mucurici', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Muniz Freire', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Muqui', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Nova Venécia', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Pancas', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Pedro Canário', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Pinheiros', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Piúma', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Ponto Belo', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Presidente Kennedy', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Rio Bananal', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Rio Novo do Sul', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Santa Leopoldina', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Santa Maria de Jetibá', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Santa Teresa', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('São Domingos do Norte', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('São Gabriel da Palha', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('São José do Calçado', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('São Mateus', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('São Roque do Canaã', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Serra', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Sooretama', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Vargem Alta', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Venda Nova do Imigrante', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Viana', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Vila Pavão', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Vila Valério', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Vila Velha', 1, getdate())
insert into Cidade (nome, ativo, dataCadastro) values ('Vitória', 1, getdate())

